nouns = "cosa, thing, noun,
anno, year, noun,
uomo, man, noun,
giorno, day, noun,
volta, time, noun,
casa, home, noun,
parte, part, noun,
vita, life, noun,
tempo, time (weather), noun,
donna, woman, noun,
mano, hand, noun,
occhio, eye, noun,
ora, now, noun,
signore, Mr., noun,
paese, country (town), noun,
momento, moment, noun,
modo, way, noun,
copertura, cover (coverage), noun,
mondo, world, noun,
radio, radio, noun,
parola, word, noun,
padre, father, noun,
punto, point, noun,
lavoro, work (job), noun,
stato, state, noun,
caso, case, noun,
città, city, noun,
guerra, war, noun,
strada, street (road), noun,
figlio, son, noun,
notte, night, noun,
voce, voice, noun,
nome, name, noun,
lattina, can (tin), noun,
sera, evening, noun,
acqua, water, noun,
amico, friend, noun,
gente, people, noun,
amore, love, noun,
storia, history (story), noun,
aria, air, noun,
forza, power (might), noun,
test, test, noun,
testa, head, noun,
ragione, reason, noun,
mare, sea, noun,
mese, month, noun,
capo, head (leader), noun,
luce, light, noun,
sole, Sun, noun,
famiglia, family, noun,
piede, foot, noun,
persona, person, noun,
via, street, noun,
signora, Mrs., noun,
governo, government, noun,
senso, sense, noun,
opera, Opera, noun,
prodotto, product, noun,
festa, party, noun,
gioco, game, noun,
prova, test, noun,
campagna, countryside, noun,
fiore, flower, noun,
sala, room (hall), noun,
misura, measure, noun,
posizione, position, noun,
natura, nature, noun,
ufficio, office, noun,
specie, species, noun,
successo, success, noun,
zona, area, noun,
fuoco, fire, noun,
soldato, soldier, noun,
vista, view (sight), noun,
libertà, freedom, noun,
risultato, result, noun,
importanza, importance, noun,
dubbio, doubt, noun,
ricerca, research, noun,
dio, God, noun,
figura, figure, noun,
piazza, square, noun,
questione, question, noun,
nemico, enemy, noun,
pena, punishment, noun,
motivo, reason, noun,
esperienza, experience, noun,
ricordo, memory, noun,
albero, tree, noun,
politica, policy, noun,
processo, process, noun,
vino, wine, noun,
porta, door, noun,
sud, south, noun,
ovest, west, noun,
est, east, noun,
sogno, dream, noun,
schiava, slave, noun,
cane, dog, noun,
isola, island, noun,
movimento, movement, noun,
mente, mind, noun,
occasione, opportunity, noun,
prezzo, price, noun,
causa, cause, noun,
periodo, period, noun,
sviluppo, development, noun,
sorella, sister, noun,
effetto, effect, noun,
giardino, garden, noun,
attività, activities, noun,
volontà, will, noun,
volto, face, noun,
base, basis, noun,
carattere, character, noun,
coscienza, consciousness, noun,
guardia, guard, noun,
memoria, memory, noun,
pista, track (trail), noun,
terreno, ground (soil), noun,
suolo, soil, noun,
terra, ground (land), noun,
animale, animal, noun,
direzione, direction, noun,
eccellenza, excellence, noun,
malattia, disease, noun,
scienza, science, noun,
funzione, function, noun,
tuta, suit, noun,
conseguenza, result, noun,
parete, wall, noun,
dente, tooth, noun,
distanza, distance, noun,
genitore, parent, noun,
gusto, taste, noun,
impressione, impression, noun,
istituto, institute, noun,
quadro, painting, noun,
attenzione, attention, noun,
chiamata, call (calling), noun,
autore, author, noun,
difficoltà, difficulty (trouble), noun,
passione, passion, noun,
commissione, commission, noun,
particolare, particular (detail), noun,
sega, saw, noun,
dito, finger, noun,
inizio, start, noun,
programma, program, noun,
spettacolo, show, noun,
titolo, title, noun,
comunicazione, communication, noun,
fenomeno, phenomenon, noun,
maggio, May, noun,
stampa, press (print), noun,
denaro, money, noun,
copia, copy, noun,
destino, destiny, noun,
dovere, duty, noun,
ferro, iron, noun,
ferrovia, rail (railway), noun,
punta, tip, noun,
regno, kingdom, noun,
epoca, era, noun,
luna, moon, noun,
provincia, province, noun,
voglia, wish, noun,
differenza, difference, noun,
controllo, control, noun,
grazia, grace, noun,
passato, past, noun,
spazio, space (outer space), noun,
stella, star, noun,
gara (corsa), race, noun,
erba, grass, noun,
massa, mass, noun,
origine, origin, noun,
polizia, police, noun,
soluzione, solution, noun,
chilometro, kilometer, noun,
madre, mother, noun,
paura, fear, noun,
cuore, heart, noun,
messaggio, post (message), noun,
idea, idea, noun,
fondo, background (bottom), noun,
esempio, example, noun,
ordine, order, noun,
posto, place (spot), noun,
campo, field, noun,
faccia, face, noun,
moglie, wife, noun,
ragazzo, boy, noun,
bisogno, need (necessity), noun,
cielo, sky, noun,
bevanda, drink (beverage), noun,
letto, bed, noun,
fronte, front, noun,
conto, bill, noun,
corpo, body, noun,
numero, number, noun,
ministro, minister, noun,
benzina, petrol (gas), noun,
problema, problem, noun,
costa, coast, noun,
chiesa, church, noun,
braccio, arm, noun,
supporto, support, noun,
bambino, child, noun,
pensiero, thought, noun,
pace, peace, noun,
morte, death, noun,
fine, end, noun,
forma, form (shape), noun,
resto, rest, noun,
popolo, people, noun,
società, society, noun,
studio, study, noun,
legge, law, noun,
libro, book, noun,
figlia, daughter, noun,
segmento, segment, noun,
sostanza, substance, noun,
divisione, division, noun,
rosa, rose, noun,
deserto, desert, noun,
pistola, gun, noun,
pianeta, planet, noun,
triangolo, triangle, noun,
ruscello, stream, noun,
campana, bell, noun,
corda, string (chord), noun,
poesia, peom, noun,
mais, corn, noun,
ala, wing, noun,
sentiero, pathway (trail), noun,
vapore, steam (vapor), noun,
gamma, range (gamut), noun,
palla, ball, noun,
coppia, pair (couple), noun,
cerchio, circle, noun, 
ghiaccio, ice, noun,
dimensione, size (dimensions), noun,
soggetto, subject, noun,
lunghezza, length, noun,
regola, rule (regulation), noun, 
pioggia, rain, noun,
mappa, map, noun,
modella, pattern (model), noun,
verbo, verb, noun,
fatto, fact, noun,
coda, tail, noun,
mente, mind (brains), noun,
oceano, ocean, noun,
finale, final, noun,
nota, note, noun,
bugia, lie (falsehood), noun,
sedia, chair, noun,
raggio, spoke (radius), noun,
sabbia, sand, noun,
temperatura, temperature, noun,
studente, student, noun,
cibo, food, noun,
pesce, fish, noun,
fattoria, farm, noun,
olio, oil, noun,
pausa, break, noun
seme, seed, noun,
fila, row, noun,
primavera, spring, noun,
banca, bank, noun,
rabbia, anger, noun,
naso, nose, noun,
sale, salt, noun,
sbaglio, mistake, noun,
colonna, column, noun,
rumore, noise, noun,
camion, truck, noun,
scarpa, shoe, noun,
evento, event, noun,
capello, hat, noun,
grafico, chart (graph), noun,
totale, total, noun,
vittoria, victory (win), noun,
scheda, card (form), noun,
cappotto, coat, noun,
punteggio, score, noun,
magnete, magnet, noun,
abilità, skill (ability), noun,
capacità, ability (capacity), noun,
divertimento, fun, noun,
bordo, edge, noun,
mucca, cow, noun,
vetro, glass, noun, 
danza, dance, noun,
onda, wave, noun,
esperimento, experiment, noun,
nube, cloud, noun,
sorpresa, surprise, noun,
radice, root, noun,
piega, crease, noun,
suono, sound, noun,
calore, heat, noun,
superficie, surface, noun,
canzone, song, noun,
uccello, bird, noun,
resto, rest, noun,
luogo, place, noun,
condizione, condition, noun,
professore, teacher, noun,
marito, husband, noun,
verità, truth, noun,
segno, sign, noun,
diritto, right, noun,
lettera, letter, noun,
ragazza, girl, noun,
scuola, school, noun,
camera, room, noun,
gruppo, group, noun,
discorso, speech, noun,
centro, center, noun,
secolo, century, noun,
mezzo, half (middle), noun,
tipo, guy (type), noun,
colpa, fault, noun,
rispetto, respect, noun,
scena, scene, noun,
oggetto, object, noun,
possibilità, possibility, noun,
mamma, mom, noun,
presenza, presence, noun,
teatro, theater, noun,
caffè, coffee, noun,
principio, principle, noun,
miniera, mine (source), noun,
termine, term, noun,
lingua, tongue (language), noun,
pezzo, piece, noun,
capello, hair, noun,
regione, region, noun,
monte, mountain, noun,
università, university, noun,
treno, train, noun,
inverno, winter, noun,
nazione, nation, noun,
pagina, page, noun,
scopo, purpose, noun,
compagno, partner, noun,
necessità, need, noun,
potere, power, noun,
musica, music, noun,
dottore, doctor, noun,
sentimento, feeling, noun,
nave, ship, noun,
pietra, stone, noun,
produzione, production, noun,
speranza, hope, noun,
dolore, ache, noun,
carne, meat, noun,
proposito, purpose, noun,
elemento, element, noun,
stazione, railway station, noun,
materia, matter, noun,
salita, climb (ascent), noun,
scala, ladder, noun,
maniera, way, noun,
arma, weapon, noun,
autorità, authority, noun,
pneumatico, tire (tyre), noun,
i bit, bit, noun,
i esercizio, exercise, noun,
quote, share (portion), noun,
gamba, leg, noun,
patria, homeland, noun,
albergo, hotel, noun,
gioia, joy, noun,
argomento, topic, noun,
sguardo, look, noun,
relazione, report, noun,
classe, class, noun,
pipistrello, bat (animal), noun,
battaglia, battle, noun,
viso, face, noun,
slittamento, slip (fall), noun,
gesto, gesture, noun,
mattino, morning, noun,
opinione, opinion, noun,
ponte, bridge, noun,
sorriso, smile, noun,
frase, phrase, noun,
limite, limit, noun,
ritorno, return, noun,
bosco, wood, noun,
esame, exam, noun,
bar, bar, noun,
lato, side, noun,
operazione, operation, noun,
pranzo, lunch, noun,
costa, it costs, noun,
prato, meadow, noun,
repubblica, republic, noun,
valle, valley, noun,
nord, north, noun,
fatica, fatigue, noun,
odore, smell, noun,
articolo, article, noun,
costruzione, construction, noun,
rivoluzione, revolution, noun,
fermata, stop (stoppage), noun,
zia, aunt, noun,
confronto, comparison, noun,
potenza, power (strenght), noun,
sforzo, effort, noun,
sicurezza, safety, noun,
ufficiale, official, noun,
crisi, crisis, noun,
cucina, kitchen, noun,
gatto, cat, noun,
pietà, pity, noun,
territorio, territory, noun,
attimo, moment, noun,
civiltà, civilization, noun,
contatto, contact, noun,
errore, error, noun,
fretta, hurry, noun,
intenzione, intention, noun,
cultura, culture, noun,
giudizio, judgement, noun,
spesa, expense, noun,
aiuto, help, noun,
ambiente, environment, noun,
animo, mind (character), noun,
bestia, beast, noun,
cortile, courtyard, noun,
pelle, skin, noun,
proposta, proposal, noun,
riva, shore, noun,
segretario, secretary, noun,
abito, dress, noun,
roccia, rock, noun,
chiave, key, noun,
operaio, worker, noun,
corso, course, noun,
finestra, window, noun,
ripetizione, repetition, noun,
arte, art, noun,
sistema, system, noun,
piano, plan (scheme), noun,
bocca, mouth, noun,
anima, soul, noun,
palazzo, palace, noun,
passo, step, noun,
giornata, day, noun,
servizio, service, noun,
rapporto, relationship, noun,
design, design, noun,
milione, million, noun,
stanza, room, noun,
valore, value, noun,
colpo, blow (strike), noun,
sangue, blood, noun,
interesse, interest, noun,
spalla, shoulder, noun,
silenzio, silence, noun,
signorina, young lady, noun,
ombra, shadow, noun,
azione, action, noun,
vento, wind, noun,
mattina, morning, noun,
colore, color, noun,
presidente, president, noun,
consiglio, advice, noun,
principe, prince, noun,
viaggio, travel (trip), noun,
rotolo, roll (reel), noun,
richiesta, claim, noun,
genere, kind, noun,
cima, top (peak), noun,
i top, top (shirt), noun,
giornale, newspaper, noun,
aereo, plane (aircraft), noun,
offerta, offer, noun,
unità, unit (unity), noun,
spirito, spirit, noun,
cavallo, horse, noun,
record, record, noun, 
muro, wall, noun,
situazione, situation, noun,
linea, line, noun,
giro, round (lap/ride), noun,
automobile, car, noun,
atto, act (action), noun,
sostantivo, noun (substantive), noun,
aspetto, appearance, noun,
età, age, noun,
fortuna, luck, noun,
carica, charge, noun,
set, set, noun,
oro, gold, noun,
partita, game (match), noun,
partito, party, noun,
macchina, machine, noun,
carta, paper, noun,
minuto, minute, noun,
tratto, stretch, noun,
settimana, week, noun,
notizia, news, noun,
fratello, brother, noun,
realtà, reality, noun,
industria, industry, noun,
cambiamento, change (shift), noun,
piacere, pleasure, noun,
maestro, master, noun,
personaggio, character, noun,
pomeriggio, afternoon, noun,
fianco, side, noun,
bambina, child, noun,
bellezza, beauty, noun,
domanda, question, noun,
pianta, plant, noun,
pubblico, public, noun,
sede, seat, noun,
affare, deal, noun,
bene, well, noun,
metà, half, noun,
papà, Pope, noun,
fiume, river, noun,
lotta, fight, noun,
mercato, market, noun,
vigore, force (vigor), noun,
angolo, angle (corner), noun,
compagnia, company (fellowship), noun,
le azienda, company (business), noun,
espressione, expression, noun,
negozio, shop (store), noun,
labbro, lip, noun,
villa, villa, noun,
desiderio, desire (wish), noun,
serie, series, noun,
visita, visit, noun,
coraggio, courage, noun,
direttore, director, noun,
avviso, notice (warning), noun,
esercito, army, noun,
grado, degree, noun,
padrone, master, noun,
risposta, reply (answer), noun,
tavola, table, noun,
immagine, image (picture), noun,
montagna, mountain, noun,
energia, energy (power), noun,
anello, ring (loop), noun,
fede, wedding ring (faith), noun,
squadra, team, noun,
pane, bread, noun,
seguito, following, noun,
estate, summer, noun,
film, movie, noun,
frutta, fruit, noun,
onore, honor, noun,
pericolo, danger, noun,
scrittore, writer, noun,
collina, hill, noun,
caccia, hunt (chase), noun,
zio, uncle, noun,
difesa, defence, noun,
metro, meter, noun,
collo, neck, noun,
cura, care (treatment), noun,
disposizione, layout, noun,
Domenica, Sunday, noun,
nascita, birth (origin), noun,
giovanotto, young man, noun,
poeta, poet, noun,
stagione, season, noun,
peso, weight, noun,
tono, tone, noun,
croce, cross, noun,
decisione, decision, noun,
poesia, poetry, noun,
fiducia, confidence, noun,
bastone, stick, noun,
filo, wire, noun,
folla, crowd, noun,
qualità, quality, noun,
roba, stuff, noun,
conoscenza, knowledge, noun,
favore, favor, noun,
popolazione, population, noun,
strumento, tool, noun,
uso, use, noun,
vestito, dress, noun,
commercio, business (trade), noun,
cantiere, yard (building site), noun,
fabbrica, factory, noun,
giugno, June, noun,
giustizia, justice, noun,
avvocato, lawyer, noun,
massa, mass, noun,
orecchio, ear, noun,
sonno, sleep, noun,
congresso, congress, noun,
porto, port, noun,
calcio, football, noun,
fantasia, fantasy, noun,
matrimonio, marriage, noun,
medico, doctor, noun,
ospedale, hospital, noun,
finitura, finish, noun,
pianura, flat land, noun,
posa, pose, noun,
tavolo, table, noun,
fame, hunger, noun,
latte, milk, noun,
merito, merit, noun,
attore, actor, noun,
ricchezza, wealth, noun,
cravatta, necktie, noun,
sacrificio, sacrifice, noun,
atteggiamento, attitude, noun,
vece, stead (place), noun,
concetto, concept, noun,
le alimentazione, supply (feed/diet), noun,
mestiere, craft, noun,
attesa, waiting, noun,
lavaggio, wash (washing), noun,
bagno, bathroom, noun,
fornitura, supply, noun,
foglia, leaf, noun,
istante, instant, noun,
lago, lake, noun,
contadino, farmer, noun,
vela, sail (sailing), noun,
orologio, clock / watch, noun,
taglio, cut (edge), noun,
suddetto, said (aforementioned), noun,
pratica, practice (experience), noun,
discussioni, discussions (talks), noun,
mosto, must (duty), noun".gsub("\n", ' ').gsub("\t", ' ').split(",")

adjectives = "questo, this, adjective,
quello, that (one), adjective,
silenzioso, silent, adjective, 
più, more, adjective,
tutto, all (whole), adjective,
corretta, correct, adjective,
originale, original, adjective,
grasso, fat, adjective,
corrente, current, adjective,
morto, dead, adjective,
tagliente, sharp (trenchant), adjective,
acuta, sharp (keen), adjective, 
liquido, liquid, adjective,
morbida, soft, adjective,
generale, general, adjective,
probabile, probable, adjective,
lento, slow, adjective,
gratuita, free (gratis), adjective,
spessa, thick, adjective,
spento, off, adjective, 
aperto, open, adjective,
principale, main (principal), adjective,
pochi, few, adjective,
pulita, clean, adjective,
esatta, exact, adjective,
giusta, fair (right), adjective,
sbagliato, wrong (mistaken), adjective,
opposto, opposite, adjective,
doppia, double, adjective,
luminosa, bright, adjective,
selvaggia, wild, adjective,
materiale, material (corporeal), adjective,
pesante, heavy, adjective,
dritto, straight, adjective, 
asciutto, dry, adjective,
occupato, busy (occupied), adjective,
suo, his, adjective,
altro, other (else), adjective,
mio, my, adjective,
quale, which, adjective,
tanto, much, adjective,
grande, great (large), adjective,
poco, little, adjective,
molto, very, adjective,
nostro, our, adjective,
stesso, same, adjective,
primo, first, adjective,
loro, their, adjective,
ogni, every (each), adjective,
proprio, own, adjective,
solo, only, adjective,
quanto, how much, adjective,
bello, beautiful, adjective,
qualche, some, adjective, 
nuovo, new, adjective, 
certo, certain (of course), adjective, 
vero, true, adjective,
buono, good, adjective,
tuo, your, adjective,
nessuno, nobody, adjective,
alcuno, any, adjective,
rotto, broken, adjective,
italiano, Italian, adjective,
separato, separate, adjective,
ultimo, last, adjective,
vecchio, old, adjective,
piccolo, small (tiny), adjective,
troppo, too much, adjective,
di base, basic, adjective,
tale, such, adjective,
giovane, young, adjective,
alto, tall, adjective,
vostro, your, adjective,
diverso, different, adjective,
meglio, better, adjective,
lungo, long, adjective,
povero, poor, adjective,
maggiore, greater, adjective,
fatto, done (made), adjective,
mezzo, half, adjective,
secondo, second, adjective,
perso, lost, adjective,
lontano, far, adjective,
vicino, close (near), adjective,
possibile, possible, adjective,
caro, dear, adjective,
pieno, full, adjective,
nero, black, adjective,
particolare, particular (special), adjective,
bianco, white, adjective, 
forte, strong (loud), adjective, 
politico, politic, adjective,
attuale, current, adjective,
latino, Latin, adjective,
impossibile, impossible, adjective,
sereno, serene, adjective,
puro, pure, adjective,
normale, normal, adjective,
perfetto, perfect, adjective,
piano, plan, adjective,
caratteristico, characteristic, adjective,
russo, Russian, adjective,
continuo, continuous, adjective, 
stupido, stupid, adjective,
estremo, extreme, adjective, 
grigio, grey, color,
marrone, brown, color, 
reale, real, adjective, 
interessante, interesting, adjective,
medesimo, same, adjective,
religioso, religious, adjective,
ampio, large (wide), adjective,
biondo, blond, adjective,
ufficiale, official, adjective,
attento, careful, adjective,
enorme, huge, adjective,
sottile, thin, adjective,
triste, sad, adjective,
minimo, minimum, adjective,
privato, private, adjective,
rapido, rapid, adjective,
quarto, fourth, adjective,
diretto, direct, adjective,
nobile, noble, adjective,
pericoloso, dangerous, adjective,
giallo, yellow, adjective,
pazzo, crazy, adjective,
sacro, sacred, adjective,
comodo, comfortable, adjective,
elettrico, electric, adjective,
assoluto, absolute, adjective,
cristiano, Christian, adjective,
antico, ancient, adjective,
rosso, red, adjective,
chiaro, clear, adjective,
unico, single, adjective,
sicuro, sure (safe), adjective,
veloce, quick, adjective,
importante, important, adjective,
vario, varied, adjective,
giusto, quite right, adjective,
francese, French, adjective,
vivo, I live, adjective,
generale, general, adjective,
ricco, rich, adjective,
grosso, big, adjective,
necessario, necessary, adjective,
libero, free, adjective,
nazionale, national, adjective,
basso, bass (low), adjective,
semplice, simple, adjective,
grave, serious, adjective,
pubblico, public, adjective,
comune, common, adjective,
freddo, cold, adjective,
economico, cheap, adjective,
felice, happy (glad), adjective,
difficile, difficult, adjective,
tedesco, German, adjective,
breve, short, adjective,
pronto, ready, adjective,
serio, serious, adjective,
presente, present, adjective,
migliore, best, adjective,
facile, easy, adjective,
terzo, third, adjective,
caldo, hot, adjective,
estero, abroad, adjective,
largo, wide, adjective,
pricipale, pricipale, adjective,
nato, born, adjective,
verde, green, adjective,
romano, Roman, adjective,
umano, human, adjective,
inutile, useless, adjective,
moderno, modern, adjective,
numeroso, numerous, adjective,
simile, similar, adjective,
fresco, fresh (cool), adjective,
militare, military, adjective,
americano, American, adjective,
vuoto, empty, adjective,
ciascuno, each, adjective,
tranquillo, quiet, adjective,
contento, happy, adjective,
scritto, written, adjective,
storico, historical, adjective,
superiore, higher, adjective,
inglese, English, adjective,
fermo, stationary, adjective,
solito, usual, adjective,
buio, dark, adjective,
strano, strange, adjective,
noto, known, adjective,
prossimo, next one (neighbor), adjective,
profondo, deep, adjective,
sociale, social, adjective,
cattivo, bad, adjective,
massimo, maximum, adjective,
intero, full, adjective,
uguale, equal, adjective,
bravo, good boy, adjective,
brutto, ugly, adjective,
preciso, accurate, adjective,
qualsiasi, any, adjective,
improvviso, sudden, adjective,
famoso, famous, adjective,
straniero, foreigner, adjective,
civile, civil, adjective,
internazionale, international, adjective,
interno, internal, adjective,
vasto, extensive, adjective, 
segreto, secret, adjective, 
greco, Greek, adjective, 
naturale, natural, adjective, 
sinistro, left, adjective, 
duro, hard, adjective, 
stanco, tired, adjective, 
azzurro, light blue, adjective, 
recente, recent, adjective, 
notevole, remarkable, adjective, 
cittadino, citizen, adjective, 
destro, right, adjective, 
europeo, European, adjective, 
zitto, quiet, adjective, 
medio, average, adjective, 
qualunque, whatever, adjective, 
straordinario, extraordinary, adjective, 
nudo, naked, adjective,
futuro, future, adjective,
cattolico, Catholic, adjective,
capace, able, adjective,
industriale, industrial, adjective, 
personale, staff, adjective, 
centrale, central, adjective, 
tecnico, technical, adjective, 
dolce, sweet, adjective, 
leggero, light, adjective, 
morale, moral, adjective, 
utile, helpful, adjective, 
contrario, contrary, adjective, 
speciale, special, adjective, 
peggio, worse, adjective, 
minore, lower, adjective".gsub("\n", ' ').gsub("\t", ' ').split(",")

verbs = "essere, to be, verb,
avere, to have, verb,
dire, to say, verb,
potere, can, verb,
volere, want, verb,
sapere, to know, verb,
stare, to stay, verb,
dovere, must, verb,
vedere, to see, verb,
andare, to go, verb,
venire, to come, verb,
dare, to give, verb,
parlare, to speak, verb,
trovare, to find, verb,
sentire, to feel (to hear), verb,
lasciare, to leave, verb,
prendere, to take, verb,
guardare, to look, verb,
mettere, to put, verb,
pensare, to think, verb,
passare, to pass, verb,
credere, to believe, verb,
portare, to bring, verb,
parere, to seem, verb,
tornare, to return, verb,
sembrare, to seem (to look like), verb,
tenere, to keep, verb,
capire, to understand, verb,
morire, to die, verb,
chiamare, to call, verb,
conoscere, to know, verb,
rimanere, to stay, verb,
chiedere, to ask, verb,
cercare, to search for, verb,
entrare, to come in, verb,
vivere, to live, verb,
aprire, to open, verb,
uscire, to go out, verb,
ricordare, to remember, verb,
bisognare, to need, verb,
cominciare, to begin, verb,
rispondere, to answer (to reply), verb,
aspettare, to wait (expect), verb,
riuscire, to succeed, verb,
chiudere, to close, verb,
finire, to finish, verb,
arrivare, to arrive, verb,
scrivere, to write, verb,
diventare, to become, verb,
restare, to remain, verb,
seguire, to follow, verb,
bastare, to suffice, verb,
perdere, to lose, verb,
rendere, to make (big / small), verb,
correre, to run, verb,
salvare, to save, verb,
vestire, to dress, verb,
costruire, to build, verb,
camminare, to walk, verb,
ritrovare, to find again, verb,
durare, to last, verb,
accendere, to turn on, verb,
evitare, to avoid, verb,
immaginare, to imagine, verb,
ridurre, to reduce, verb,
contenere, to contain, verb,
fissare, to fix, verb,
costringere, to force, verb,
abbandonare, to abandon, verb,
attendere, to wait for, verb,
preferire, to prefer, verb,
scegliere, to choose, verb,
avvertire, to warn, verb,
proporre, to propose, verb,
temere, to fear, verb,
esprimere, to express, verb,
spingere, to push, verb,
salutare, to greet, verb,
udire, to hear, verb,
alleviare, to ease, verb,
confrontare, to compare, verb,







difendere, to stick up for, verb,
dirigere, to direct, verb,
cantare, to sing, verb,
sorgere, to rise, verb,
assicurare, to ensure, verb,
assumere, to hire, verb,
tendere, to tend, verb,
dividere, to divide, verb,
scusare, to excuse, verb,
mantenere, to maintain, verb,
ritenere, to consider, verb,
concludere, to conclude, verb,
saltare, to jump, verb,
stabilire, to establish, verb,
appartenere, to belong, verb,
possedere, to possess, verb,
risultare, to result, verb,
suonare, to play, verb,
coprire, to cover up, verb,
insegnare, to teach, verb,
affermare, to assert, verb,
rivelare, to reveal, verb,
conservare, to preserve, verb,
risolvere, to solve, verb,
concedere, to grant, verb,
limitare, to limit, verb,
abitare, to live, verb,
convincere, to convince, verb,
comprare, to buy, verb,
legare, to tie, verb,
sostenere, to sustain, verb,
nascere, to be born, verb,
presentare, to introduce, verb,
trattare, to deal, verb,
piacere, to like, verb,
continuare, to continue, verb,
partire, to leave, verb,
servire, to serve, verb,
giungere, to reach, verb,
fermare, to stop, verb,
apparire, to appear, verb,
amare, to love, verb,
esistere, to exist, verb,
intendere, to hear, verb,
salire, to go up, verb,
mancare, to miss, verb,
ridere, to laugh, verb,
lavorare, to work, verb,
alzare, to raise up, verb,
riconoscere, to recognize, verb,
sedere, to sit down, verb,
leggere, to read, verb,
cadere, to fall, verb,
mangiare, to eat, verb,
dormire, to sleep, verb,
raggiungere, to reach, verb,
comprendere, to understand, verb,
scendere, to alight, verb,
compiere, to fulfill, verb,
toccare, to touch, verb,
considerare, to consider, verb,
muovere, to move, verb,
stringere, to tighten, verb,
mandare, to send, verb,
domandare, to ask, verb,
ascoltare, to listen, verb,
decidere, to decide, verb,
ricevere, to receive, verb,
osservare, to observe, verb,
permettere, to allow, verb,
avvenire, to occur, verb,
spiegare, to explain, verb,
raccogliere, to collect, verb,
ottenere, to obtain, verb,
offrire, to offer, verb,
mostrare, to exhibit, verb,
accompagnare, to accompany, verb,
dimenticare, to forget, verb,
pregare, to pray, verb,
raccontare, to tell, verb,
bere, to drink, verb,
ritornare, to return, verb,
cambiare, to change, verb,
dimostrare, to demonstrate, verb,
sperare, to hope, verb,
sposare, to marry, verb,
ammettere, to admit, verb,
fuggire, to run away, verb,
liberare, to free, verb,
riferire, to report, verb,
svegliare, to wake up, verb,
capitare, to happen, verb,
posare, to place, verb,
impedire, to prevent, verb,
gettare, to throw, verb,
vendere, to sell, verb,
distinguere, to distinguish, verb,
offendere, to offend, verb,
rimettere, to return, verb,
rompere, to break, verb,
godere, to enjoy, verb,
imporre, to impose, verb,
significare, to mean, verb,
desiderare, to desire, verb,
divertire, to amuse, verb,
volgere, to turn, verb,
giudicare, to judge, verb,
produrre, to produce, verb,
avvicinare, to approach, verb,
diffondere, to spread, verb,
ordinare, to sort, verb,
invitare, to invite, verb,
discutere, to discuss, verb,
sbagliare, to make a mistake, verb,
adattare, to adpat, verb,
badare, to look after, verb,
tagliare, to cut, verb,
pubblicare, to publish, verb,
attaccare, to attack, verb,
imparare, to learn, verb,
prevedere, to forecast, verb,
scappare, to run away, verb,
spegnere, to switch off, verb,
annunciare, to announce, verb,
baciare, to kiss, verb,
esporre, to expose, verb,
attraversare, go across, verb,
fornire, to provide, verb,
segnare, to mark, verb,
superare, to overcome, verb,
rivedere, to review, verb,
allontanare, to remove, verb,
ammazzare, to kill, verb,
accogliere, to receive, verb,
voltare, to turn, verb,
preoccupare, to worry, verb,
provocare, to cause, verb,
riempire, to fill, verb,
partecipare, to take part, verb,
piantare, to plant, verb,
rientrare, to re-enter, verb,
richiedere, to request, verb,
nascondere, to hide, verb,
ripetere, to repeat, verb,
scoprire, to discover, verb,
preparare, prepare, verb,
scorrere, to slide, verb,
rappresentare, to represent, verb,
riprendere, to resume, verb,
costituire, to constitute, verb,
incontrare, to meet, verb,
valere, be worth, verb,
accorgersi, to notice, verb,
provare, to try, verb,
formare, to form, verb,
uccidere, to kill, verb,
tirare, to pull, verb,
togliere, to remove, verb,
notare, to notice, verb,
aggiungere, to add, verb,
succedere, to happen, verb,
pagare, to pay, verb,
aderire, to join, verb,
tentare, to attempt, verb,
accadere, to happen, verb,
creare, to create, verb,
importare, to import, verb,
pesare, to weigh, verb,
usare, to use, verb,
accetta, to accept, verb,
indicare, to indicate, verb,
buttare, to throw, verb,
battere, to beat, verb,
interessare, to interest, verb,
sorridere, to smile, verb,
condurre, to conduct, verb,
disporre, to have, verb,
unire, to merge, verb,
aiutare, to help, verb,
piangere, to cry, verb,
girare, to turn, verb,
levare, to lift, verb,
soffrire, to suffer, verb,
recare, to cause, verb,
riguardare, to concern, verb,
rivolgere, to turn, verb,
tacere, to be silent, verb,
occorrere, to take, verb,
porre, to place, verb,
vincere, to win, verb,
svolgere, to perform, verb,
studiare, to study, verb,
crescere, to grow up, verb,
divenire, to become, verb,
gridare, to shout, verb,
dichiarare, to declare, verb,
contare, to count, verb,
giocare, to play, verb,
assistere, to assist, verb,
aumentare, to increase (raise), verb,
lanciare, to launch, verb,
determinare, to determine, verb,
scherzare, to joke, verb,
elevare, to raise, verb,
promettere, to promise, verb,
scomparire, to disappear, verb,
trarre, to draw, verb,
distruggere, to destroy, verb,
meritare, to deserve, verb,
dedicare, to devote, verb,
iniziare, to start, verb,
sorprendere, to surprise, verb,
trasformare, to commute, verb,
confessare, to confess, verb,
arrestare, to stop, verb,
ringraziare, to thank, verb,
riunire, to gather, verb,
volare, to fly, verb,
fondare, to found, verb,
guidare, to drive, verb,
ferire, to hurt, verb,
opporre, to oppose, verb,
procedere, to proceed, verb,
smettere, to stop, verb,
consentire, to allow, verb,
innamorarsi, to fall in love, verb,
organizzare, to organize, verb,
rifiutare, to reject, verb,
riportare, to report, verb,
dipendere, to depend, verb,
provvedere, to provide, verb,
trascinare, to drag, verb,
fumare, to smoke, verb,
scoppiare, to burst, verb,
sognare, to dream, verb,
appoggiare, to support, verb,
armare, to arm, verb,
celebrare, to celebrate, verb,
descrivere, to describe, verb,
resistere, to resist, verb,
bruciare, to burn, verb,
colpire, to hit, verb,
estendere, to extend, verb,
staccare, to remove, verb,
affrontare, to face up to, verb,
avanzare, to push forward, verb,
comporre, to compose, verb,
escludere, to exclude, verb,
figurare, to appear, verb,
insistere, to insist, verb,
praticare, to practice, verb".gsub("\n", ' ').gsub("\t", ' ').split(",")

other = "il, the, other,
di, of, other,
e, is, other,
a, to, other,
un, a, other,
in, in, other,
che, that (which), other,
non, not, other,
si, Yes, other,
da, from, other,
lo, the, other,
per, for, other,
con, with, other,
ma, but, other,
come, how, other,
su, up, other,
mi, me, other,
anche, also (even), other,
o, or, other,
io, I, other,
se, self, other,
perché, because, other,
li, there, other,
ci, us, other,
ne, neither, other,
alcuni, several (some), other,
lei, she, other,
ancora, yet, other,
mezzogiorno, noon, other,
tu, you, other,
lui, he, other,
senza, without, other,
bene, well, other,
cui, which, other,
chi, who, other,
già, already, other,
dopo, after, other,
uno, one, number,
due, two, number,
tre, three, number,
quattro, four, number,
cinque, five, number,
sei, six, number,
sette, seven, number,
otto, eight, number,
nove, nine, number,
dieci, ten, number,
venti, twenty, number,
cento, one hundred, number,
noi, we, other,
dove, where, other,
qui, here, other,
no, no, other,
allora, then, other,
tra, between (among), other,
vi, you, other,
ora, now (hour), other,
fra, between, other,
prima, before, other,
forse, perhaps, other,
sì, yes, other,
sotto, under, other,
voi, you, other,
fino, till, other,
oggi, today, other,
quasi, almost, other,
pure, also, other,
egli, he, other,
mentre, while, other,
contro, versus (against), other,
invece, instead, other,
esso, it, other,
là, there, other,
però, However, other,
né, neither, other,
subito, immediately, other,
verso, towards, other,
ciò, it, other,
tranne, except, other,
ecco, here, other,
loro, their, other,
essa, it, other,
fuori, outside, other,
meno, less (least), other,
adesso, now, other,
niente, nothing, other,
cioè, that is, other,
male, bad, other,
nulla, nothing, other,
ah, ha, other,
oh, oh, other,
quindi, then, other,
appena, as soon as, other,
insieme, together, other,
dunque, therefore, other,
dentro, inside, other,
durante, during, other,
almeno, at least, other,
secondo, second, other,
anzi, rather, other,
oramai, now, other,
oltre, over, other,
se, if (whether), other,
intorno, around, other,
sopra, above, other,
dietro, behind, other,
davanti, in front of, other,
soltanto, only, other,
infatti, indeed, other,
qualcosa, something, other,
spesso, often, other,
accordo, agreement, other,
ieri, yesterday, other,
davvero, really, other,
lì, there, other,
qualcuno, someone, other,
avanti, come on (forward), other,
assai, very, other,
presto, soon (early), other,
qua, here, other,
domani, tomorrow, other,
circa, about, other,
giù, down, other,
soprattutto, mostly, other,
nemmeno, not even, other,
grazie, thank you, other,
tuttavia, however, other,
appunto, just, other,
neppure, neither, other,
eh, huh, other,
veramente, really, other,
tardi, late, other,
insomma, in conclusion, other,
presso, at, other,
intanto, in the meantime, other,
lungo, long, other,
neanche, neither, other,
piuttosto, rather, other,
stasera, tonight, other,
perciò, therefore, other,
naturalmente, of course, other,
accanto, next, other,
eppure, but yet, other,
eccetera, etc, other,
finalmente, finally, other,
infine, finally, other,
poiché, as, other,
comunque, however, other,
dinanzi, before, other,
abbastanza, enough, other,
peccato, sin, other,
certamente, of course, other,
coloro, they, other,
attorno, about, other,
magari, maybe, other,
oppure, or, other,
inoltre, moreover, other,
indietro, back, other,
addosso, on, other,
addirittura, even, other,
finché, as long as, other,
perfino. even, other,
affatto, at all, other,
stamattina, this morning, other,
completamente, completely, other,
probabilmente, probably, other,
chissà, who knows, other,
ognuno, each one, other,
entro, within, other".gsub("\n", ' ').gsub("\t", ' ').split(",")

count = 0
(nouns.count/3).times do 
    ItalianWord.create(word: "#{nouns[count].strip}", meaning: "#{nouns[count + 1].strip}", pos: "noun", score: 0)
    count += 3
end

count = 0
(adjectives.count/3).times do 
    ItalianWord.create(word: "#{adjectives[count].strip}", meaning: "#{adjectives[count + 1].strip}", pos: "adjective", score: 0)
    count += 3
end

count = 0
(verbs.count/3).times do 
    ItalianWord.create(word: "#{verbs[count].strip}", meaning: "#{verbs[count + 1].strip}", pos: "verb", score: 0)
    count += 3
end

count = 0
(other.count/3).times do 
    ItalianWord.create(word: "#{other[count].strip}", meaning: "#{other[count + 1].strip}", pos: "other", score: 0)
    count += 3
end